### ISSUE TITLE
[IDEA] No display permission

### ISSUE THREAD

**Issue by ghost** [NickTheDev/AutoBroadcast#1]
If it is possible, can you add feature to turn off auto-brodcasts with permission or command (like for donors) 
Thanks

**Comment by NickTheDev** [comment]
Hello, Jake, I am a bit confused, do you mean to make it so that with a command, you can toggle whether not timed broadcasts will actually dispatch? If so, I can definitely do that :).

**Comment by ghost** [comment]
Yes thanks

**Comment by NickTheDev** [comment]
Alright, I will add that as soon as I can; the update will be pushed and uploaded on spigot some time tonight. :)

**Comment by NickTheDev** [comment]
However, I have one question, would only the person who executed the command not receive the broadcasts, or would you like no one to?

**Comment by NickTheDev** [comment]
Added requested feature, closing issue.
