### ISSUE TITLE
Invalid replacement token

### ISSUE THREAD

**Issue by PrOdIgY-CaRcAsS** [NickTheDev/AutoBroadcast#2]
Whenever /broadcast <message> is used ingame, either by a player or the server console, it returns "Invalid replacement token".

**Comment by NickTheDev** [comment]
Hmm, that is not a message sent by my plugin. This means that you have conflicting broadcast plugins. However, I recently released an update which changes the command to /autobroadcast (abc). This should resolve all conflicts.
